"""Demo data for fallback when APIs are unavailable"""

from typing import List, Dict, Any
from datetime import datetime, timedelta
import random
import uuid


def get_demo_jobs(limit: int = 20) -> List[Dict[str, Any]]:
    """Return demo job listings"""
    
    jobs = [
        {
            "external_id": "demo_1",
            "source": "demo",
            "company": "Stripe",
            "title": "Senior Frontend Engineer",
            "description": "Join Stripe's frontend team to build the future of internet commerce. You'll work on our dashboard, checkout flows, and developer tools using React, TypeScript, and modern web technologies.",
            "location": "San Francisco, CA (Remote)",
            "salary_min": 180000,
            "salary_max": 220000,
            "job_url": "https://stripe.com/jobs/example",
            "posted_at": (datetime.utcnow() - timedelta(days=2)).isoformat(),
            "job_type": "full_time",
            "remote_type": "remote",
        },
        {
            "external_id": "demo_2",
            "source": "demo",
            "company": "Vercel",
            "title": "Staff Software Engineer",
            "description": "Help build the platform that powers the modern web. Work on Next.js, our edge network, and developer experience tools. Strong TypeScript and distributed systems experience required.",
            "location": "Remote",
            "salary_min": 200000,
            "salary_max": 280000,
            "job_url": "https://vercel.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=1)).isoformat(),
            "job_type": "full_time",
            "remote_type": "remote",
        },
        {
            "external_id": "demo_3",
            "source": "demo",
            "company": "Linear",
            "title": "Full Stack Developer",
            "description": "Build the best issue tracking tool for modern software teams. We use React, TypeScript, GraphQL, and PostgreSQL. Focus on performance and beautiful UX.",
            "location": "Remote (US/EU)",
            "salary_min": 150000,
            "salary_max": 200000,
            "job_url": "https://linear.app/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=3)).isoformat(),
            "job_type": "full_time",
            "remote_type": "remote",
        },
        {
            "external_id": "demo_4",
            "source": "demo",
            "company": "Notion",
            "title": "Product Engineer",
            "description": "Shape the future of productivity tools used by millions. Work on blocks, databases, and collaboration features. React, TypeScript, and a passion for great UX required.",
            "location": "New York, NY (Hybrid)",
            "salary_min": 170000,
            "salary_max": 230000,
            "job_url": "https://notion.so/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=4)).isoformat(),
            "job_type": "full_time",
            "remote_type": "hybrid",
        },
        {
            "external_id": "demo_5",
            "source": "demo",
            "company": "Anthropic",
            "title": "ML Engineer",
            "description": "Work on cutting-edge AI safety research and build systems that help ensure AI benefits humanity. Strong ML fundamentals and Python experience required.",
            "location": "San Francisco, CA",
            "salary_min": 250000,
            "salary_max": 400000,
            "job_url": "https://anthropic.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=5)).isoformat(),
            "job_type": "full_time",
            "remote_type": "onsite",
        },
        {
            "external_id": "demo_6",
            "source": "demo",
            "company": "Bending Spoons",
            "title": "Product Intern - Evernote",
            "description": "Join our product team working on Evernote. Help analyze user data, run experiments, and ship features that millions use daily. Strong analytical skills required.",
            "location": "Milan, Italy (Remote)",
            "salary_min": 40000,
            "salary_max": 55000,
            "job_url": "https://bendingspoons.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(hours=12)).isoformat(),
            "job_type": "internship",
            "remote_type": "remote",
        },
        {
            "external_id": "demo_7",
            "source": "demo",
            "company": "Figma",
            "title": "Senior Software Engineer",
            "description": "Build the future of design tools. Work on real-time collaboration, performance, and new creative features. C++, WebAssembly, or TypeScript experience ideal.",
            "location": "San Francisco, CA",
            "salary_min": 175000,
            "salary_max": 250000,
            "job_url": "https://figma.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=6)).isoformat(),
            "job_type": "full_time",
            "remote_type": "hybrid",
        },
        {
            "external_id": "demo_8",
            "source": "demo",
            "company": "Plaid",
            "title": "Backend Engineer",
            "description": "Build APIs that power fintech. Work on high-scale systems connecting millions of users to their financial data. Go, PostgreSQL, and distributed systems experience valued.",
            "location": "Remote",
            "salary_min": 160000,
            "salary_max": 210000,
            "job_url": "https://plaid.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=7)).isoformat(),
            "job_type": "full_time",
            "remote_type": "remote",
        },
        {
            "external_id": "demo_9",
            "source": "demo",
            "company": "Datadog",
            "title": "Frontend Engineer",
            "description": "Build observability tools used by engineering teams worldwide. React, TypeScript, and data visualization experience. Love for performance and clean code.",
            "location": "Boston, MA (Hybrid)",
            "salary_min": 140000,
            "salary_max": 190000,
            "job_url": "https://datadog.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=8)).isoformat(),
            "job_type": "full_time",
            "remote_type": "hybrid",
        },
        {
            "external_id": "demo_10",
            "source": "demo",
            "company": "Supabase",
            "title": "Developer Advocate",
            "description": "Help developers succeed with Supabase. Create tutorials, speak at conferences, and engage with the community. Strong communication and technical skills required.",
            "location": "Remote (Global)",
            "salary_min": 130000,
            "salary_max": 170000,
            "job_url": "https://supabase.com/careers/example",
            "posted_at": (datetime.utcnow() - timedelta(days=2)).isoformat(),
            "job_type": "full_time",
            "remote_type": "remote",
        },
    ]
    
    # Shuffle and limit
    random.shuffle(jobs)
    return jobs[:limit]


def get_demo_applications() -> List[Dict[str, Any]]:
    """Return demo applications for UI testing"""
    return [
        {
            "id": str(uuid.uuid4()),
            "job_id": "demo_1",
            "status": "interview_scheduled",
            "match_score": 94,
            "sentinel_update": "Calendly link detected - Interview confirmed",
            "applied_at": (datetime.utcnow() - timedelta(days=5)).isoformat(),
            "jobs": {
                "company": "Stripe",
                "title": "Senior Frontend Engineer",
                "location": "San Francisco, CA (Remote)",
                "salary_min": 180000,
                "salary_max": 220000,
                "job_url": "https://stripe.com/jobs/example",
            },
        },
        {
            "id": str(uuid.uuid4()),
            "job_id": "demo_6",
            "status": "assessment",
            "match_score": 87,
            "sentinel_update": "Technical assessment received - BRGHT IQ Test",
            "deadline": (datetime.utcnow() + timedelta(days=2)).isoformat(),
            "applied_at": (datetime.utcnow() - timedelta(days=3)).isoformat(),
            "jobs": {
                "company": "Bending Spoons",
                "title": "Product Intern - Evernote",
                "location": "Milan, Italy (Remote)",
                "salary_min": 40000,
                "salary_max": 55000,
                "job_url": "https://bendingspoons.com/careers/example",
            },
        },
        {
            "id": str(uuid.uuid4()),
            "job_id": "demo_2",
            "status": "under_review",
            "match_score": 91,
            "sentinel_update": "Application viewed by recruiter",
            "applied_at": (datetime.utcnow() - timedelta(days=4)).isoformat(),
            "jobs": {
                "company": "Vercel",
                "title": "Staff Software Engineer",
                "location": "Remote",
                "salary_min": 200000,
                "salary_max": 280000,
                "job_url": "https://vercel.com/careers/example",
            },
        },
    ]
