-- JobSniper AI - Applications Table
-- Tracks user's job applications and their status

CREATE TYPE application_status AS ENUM (
  'discovered',
  'pending_approval',
  'approved',
  'applied',
  'under_review',
  'assessment',
  'interview_scheduled',
  'interview',
  'offer',
  'rejected',
  'withdrawn'
);

CREATE TABLE IF NOT EXISTS public.applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id TEXT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  
  -- Status tracking
  status application_status NOT NULL DEFAULT 'discovered',
  match_score INTEGER CHECK (match_score >= 0 AND match_score <= 100),
  match_reasons TEXT[],
  
  -- Application materials (generated by Ghostwriter)
  cover_letter TEXT,
  resume_highlights TEXT[],
  outreach_message TEXT,
  
  -- Sentinel updates
  sentinel_update TEXT,
  deadline TIMESTAMPTZ,
  
  -- User notes
  notes TEXT,
  
  -- Timestamps
  discovered_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  applied_at TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicate applications
  UNIQUE(user_id, job_id)
);

-- Enable RLS
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- RLS Policies - users can only see their own applications
CREATE POLICY "applications_select_own" ON public.applications 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "applications_insert_own" ON public.applications 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "applications_update_own" ON public.applications 
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "applications_delete_own" ON public.applications 
  FOR DELETE USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX IF NOT EXISTS applications_user_id_idx ON public.applications(user_id);
CREATE INDEX IF NOT EXISTS applications_status_idx ON public.applications(status);
CREATE INDEX IF NOT EXISTS applications_job_id_idx ON public.applications(job_id);

-- Updated at trigger
CREATE TRIGGER applications_updated_at
  BEFORE UPDATE ON public.applications
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
